# Generated by Django 4.1 on 2022-10-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_fathersname_remove_profile_melicode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/noprofile.jpg', null=True, upload_to='profile/image'),
        ),
    ]
