# Generated by Django 4.1 on 2022-10-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='accounts/images/noprofile.jpg', upload_to='images/articles'),
        ),
    ]
