# Generated by Django 4.1 on 2022-11-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='categ', to='blog.category'),
        ),
    ]
